#include "StringFormatter.h"
#include "StringEncoder.h"
void testtoUpperMutable();
void testtoUpperImmutable();
void testtoLowerMutable();
void testtoLowerImmutable();
void teststripMutable();
void teststripImmutable();
void testdispaceMutable();
void testdispaceImmutable();
void testdispecialiseMutable();
void testdispecialiseImmutable();
void testisNumeric();
void testisAlphabetic();
void testencryptionMutable();
void testencryptionImmutable();
void testdecryptionMutable();
void testdecryptionImmutable();
void testXoraliseMutable();
void testXoraliseImmutable();